model_name: mtslstm

input_data:
  daily_file: data/Cam_Le_Daily.xlsx
  hourly_file: data/Cam_Le_Dataset.xlsx

use_frequencies: ['1D', '1h']

features:
  1D: ['Luong_mua', 'Nhiet_do_cao nhat', 'Nhiet_do_thap_nhat', 'Buc_xa_mat_troi', 'Do_am_khong_khi']
  1h: ['Muc_nuoc', 'Luong_mua', 'Nhiet_do', 'Buc_xa_mat_troi', 'Boc_thoat_hoi_nuoc_tiem_nang']

target_variable: Muc_nuoc

seq_length:
  1D: 90
  1h: 336

forecast_horizon: 24

training:
  batch_size: 32
  epochs: 50
  learning_rate: 0.001
  validation_split: 0.2
